name: "YMOverride CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ExampleObjC:
    name: ObjC Example Project (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod install
        run: pod install --project-directory=Example-ObjC

      - name: Build Project
        uses: sersoft-gmbh/xcodebuild-action@v1.8.0
        with:
          workspace: Example-ObjC/Example-ObjC.xcworkspace
          scheme: Example-ObjC
          destination: name=iPhone 13 Pro
          action: test

  ExampleSwift:
    name: Swift Example Project (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod install
        run: pod install --project-directory=Example-Swift

      - name: Build Project
        uses: sersoft-gmbh/xcodebuild-action@v1.8.0
        with:
          workspace: Example-Swift/Override.xcworkspace
          scheme: Override-Example
          destination: name=iPhone 13 Pro
          action: build # TODO: Fix Nimble library issues with tests.
          
  Pods:
    name: Cocoapods Lint (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod lib lint dynamic-framework
        run: pod lib lint --fail-fast --include-podspecs=YMOverride.podspec

      - name: Run pod lib lint static-framework
        run: pod lib lint --fail-fast --use-libraries --use-modular-headers --include-podspecs=YMOverride.podspec
          
  SwiftPM:
    name: SwiftPM (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable 

      - name: Build
        run: xcodebuild -scheme YMOverride -destination generic/platform=iOS
